feat: add wrapper to tflint to expose stdout, stderr, and exitcode
terraform-linters/setup-tflint pull request #173
Opened 2023-06-08 18:41 UTC by dreinhardt-terminus

Installing a wrapper script to wrap subsequent calls of the terraform binary and expose its `STDOUT`, `STDERR`, and `exit code` as outputs named `stdout`, `stderr`, and `exitcode` respectively. This is turned off by default.

2023-06-13 01:11 UTC, bendrucker requested changes
Thanks! Couple small comments but I recognize that this is mostly borrowed from `hashicorp/setup-terraform` and kept the requests minimal.

2023-06-13 01:11 UTC, bendrucker commented on src/setup-tflint.js
> +  core.debug(files.toString());
`files` is never used except in these debug logs.

2023-06-13 01:11 UTC, bendrucker commented on src/setup-tflint.js
> +    // Install our wrapper
```suggestion
```

2023-06-13 01:11 UTC, bendrucker commented on wrapper/tflint.js
> +  return io.which(pathToCLI, check);
```suggestion
  // throws if `which` does not find a result
  return io.which(pathToCLI, true);
```

2023-06-13 01:11 UTC, bendrucker commented on wrapper/tflint.js
> +  core.setFailed(`TFlint exited with code ${exitCode}.`);
```suggestion
  core.setFailed(`TFLint exited with code ${exitCode}.`);
```

2023-06-13 15:50 UTC, dreinhardt-terminus commented on dist/index1.js
I'm just copying setup-terraform for this. Not sure if there is a better/cleaner way.

2023-06-14 18:50 UTC, bendrucker commented on dist/index1.js
I don't see it being invoked anywhere though, am I missing something?

2023-06-23 18:01 UTC, closed without merging